events {}
http {
    include mime.types;
    default_type application/octet-stream;
    server {
        listen 80;
        server_name localhost;

        location /cv1/ {
            alias /usr/share/nginx/html/cv1/;
        }
        location /cv2/ {
            alias /usr/share/nginx/html/cv2/;

        }
        location /cv3/ {
            alias /usr/share/nginx/html/cv3/;
        }
    }
}